name: App송이 기술 블로그
description: 
meta_description: "Back-End 개발자들의 App개발 도전하기!"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "http://yourblog-domain.com"
google_analytics: "UA-176074048-1"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "appsonge.github.io"
author: "App송이"

# Disqus config
disqus-shortname: ""
